name: Main

permissions:
  contents: read

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 8,20 * * *"

jobs:
  tests:
    name: Tests
    # TODO: change back to swiftlang/github-workflows and remove ref before merging
    uses: rnro/github-workflows/.github/workflows/package_test.yml@unification
    with:
      enable_windows_docker: true
      enable_macos: true
      enable_linux_static_sdk_build: true
      enable_cxx_interop: true
      enable_release_build: true
      enable_ios_xcode_build: true
      swift_flags: "--explicit-target-dependency-import-check error"
      swift_nightly_flags: "--explicit-target-dependency-import-check error"
      xcode_scheme: swift-crypto-Package
      macos_runner_pool: nightly
