name: PR

permissions:
  contents: read

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  soundness:
    name: Soundness
    # TODO: change back to swiftlang/github-workflows and remove ref before merging
    uses: rnro/github-workflows/.github/workflows/soundness.yml@unification
    with:
      license_header_check_project_name: "SwiftCrypto"
      docs_check_enabled: false

  tests:
    name: Tests
    # TODO: change back to swiftlang/github-workflows and remove ref before merging
    uses: rnro/github-workflows/.github/workflows/package_test.yml@unification
    with:
      enable_windows_docker: true
      enable_macos: true
      enable_linux_static_sdk_build: true
      enable_cxx_interop: true
      enable_ios_xcode_build: true
      swift_flags: "--explicit-target-dependency-import-check error"
      swift_nightly_flags: "--explicit-target-dependency-import-check error"
      xcode_scheme: swift-crypto-Package
      macos_runner_pool: general

  release-builds:
    name: Release builds
    # TODO: change back to swiftlang/github-workflows and remove ref before merging
    uses: rnro/github-workflows/.github/workflows/release_build.yml@unification
    with:
      enable_windows_docker: true
      swift_flags: "--explicit-target-dependency-import-check error"
      swift_nightly_flags: "--explicit-target-dependency-import-check error"

  cmake-checks:
    name: CMake checks
    uses: apple/swift-nio/.github/workflows/cmake_tests.yml@main
    with:
      update_cmake_lists_config: >-
        {
          "targets": [
            { "name": "CCryptoBoringSSL", "type": "source", "exceptions": [] },
            { "name": "CCryptoBoringSSLShims", "type": "source", "exceptions": [] },
            { "name": "CryptoBoringWrapper", "type": "source", "exceptions": [] },
            { "name": "CXKCP", "type": "source", "exceptions": [] },
            { "name": "CXKCPShims", "type": "source", "exceptions": [] },
            { "name": "Crypto", "type": "source", "exceptions": [] },
            { "name": "CryptoExtras", "type": "source", "exceptions": [] },
            { "name": "CCryptoBoringSSL", "type": "assembly", "exceptions": [ "*/AES/*.swift" ] }
          ]
        }
